/**
 * Pixel-grid mosaic compositor — the backbone of the thumbnail
 * dissolve (PLAN.md §6).
 *
 * Strategy: at swap start we build THREE progressively decimated
 * bitmaps of the incoming frame (12×7, 24×14, 48×28 cell grids),
 * plus a full-res copy. Every rAF frame afterwards is pure
 * `drawImage` of precomputed tiles — zero per-frame filtering —
 * which is how 60 simultaneous dissolves hold 60 fps.
 */

export interface MosaicLevel {
  /** Grid columns (x cells). */
  cols: number;
  /** Grid rows (y cells). */
  rows: number;
  /**
   * Offscreen canvases, one per cell, each containing that cell's
   * average color sampled from the source frame at this level.
   */
  cells: HTMLCanvasElement[];
}

export interface MosaicPyramid {
  levels: MosaicLevel[];
  width: number;
  height: number;
}

/** Cell grids for the three refinement passes (acceptance #2). */
export const GRID_LEVELS: ReadonlyArray<{ cols: number; rows: number }> = [
  { cols: 12, rows: 7 },
  { cols: 24, rows: 14 },
  { cols: 48, rows: 28 },
];

/**
 * Build the pyramid of precomputed decimated bitmaps from a decoded
 * source image. Runs once per dissolve (≈2–4 ms for a 320×180
 * frame); every subsequent frame is a batch of drawImage calls.
 */
export function buildMosaicPyramid(
  source: CanvasImageSource,
  width: number,
  height: number,
  grids: ReadonlyArray<{ cols: number; rows: number }> = GRID_LEVELS,
): MosaicPyramid {
  const scratch = document.createElement("canvas");
  scratch.width = width;
  scratch.height = height;
  const sctx = scratch.getContext("2d", { willReadFrequently: true })!;
  sctx.drawImage(source, 0, 0, width, height);

  const levels: MosaicLevel[] = grids.map(({ cols, rows }) => ({
    cols,
    rows,
    cells: extractCells(sctx, width, height, cols, rows),
  }));

  perfMarkSafe("pixelate:pyramid-built", {
    detail: { width, height, levels: grids.length },
  });

  return { levels, width, height };
}

/**
 * Extract per-cell average-color canvases at a grid resolution.
 * Each cell canvas is `cellW × cellH` pixels of solid color,
 * generated by downscaling the source to `cols × rows` pixels
 * (hardware/GPU-accelerated downscale ≈ box filter → averages),
 * reading back the tiny pixel buffer once, then painting cells.
 */
function extractCells(
  sctx: CanvasRenderingContext2D,
  width: number,
  height: number,
  cols: number,
  rows: number,
): HTMLCanvasElement[] {
  const mini = document.createElement("canvas");
  mini.width = cols;
  mini.height = rows;
  const mctx = mini.getContext("2d", { willReadFrequently: true })!;
  mctx.imageSmoothingEnabled = true;
  mctx.drawImage(sctx.canvas, 0, 0, width, height, 0, 0, cols, rows);

  const data = mctx.getImageData(0, 0, cols, rows).data;
  const cellW = Math.max(1, Math.ceil(width / cols));
  const cellH = Math.max(1, Math.ceil(height / rows));

  const cells: HTMLCanvasElement[] = [];
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4;
      const cv = document.createElement("canvas");
      cv.width = cellW;
      cv.height = cellH;
      const cx = cv.getContext("2d")!;
      cx.fillStyle = `rgb(${data[i]},${data[i + 1]},${data[i + 2]})`;
      cx.fillRect(0, 0, cellW, cellH);
      cells.push(cv);
    }
  }
  return cells;
}

/**
 * Progressive reveal bookkeeping for one dissolve: at progress p
 * (0..1), which cells of each level have "arrived" (subdivided)?
 *
 * Cells refine along a seeded diagonal wave: cell (x,y) at level L
 * is refined once p exceeds its threshold, where thresholds fan
 * out from the top-left corner with per-cell jitter (seeded noise)
 * so the sweep looks organic rather than mechanical.
 */
export interface WaveState {
  thresholds: Float32Array[]; // per level, per cell arrival threshold
  cols: number[];
  rows: number[];
}

/** Seeded PRNG (mulberry32) — deterministic per videoId. */
export function seededRandom(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Hash a videoId string to a numeric seed. */
export function hashSeed(id: string): number {
  let h = 2166136261;
  for (let i = 0; i < id.length; i++) {
    h ^= id.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * Precompute per-cell arrival thresholds for the staggered wave.
 * Level 0 (coarsest) cells arrive earliest; each finer level's
 * cells arrive later, interleaved, producing the sweeping
 * subdivision cascade 12×7 → 24×14 → 48×28 over the duration.
 */
export function buildWaveState(
  grids: ReadonlyArray<{ cols: number; rows: number }> = GRID_LEVELS,
  seed = 1,
): WaveState {
  const rand = seededRandom(seed);
  const thresholds: Float32Array[] = [];
  const cols: number[] = [];
  const rows: number[] = [];

  grids.forEach(({ cols: c, rows: r }, li) => {
    const th = new Float32Array(c * r);
    // Each level occupies a band of the timeline; finer levels later.
    const bandStart = li / grids.length;
    const bandEnd = (li + 1) / grids.length;
    for (let y = 0; y < r; y++) {
      for (let x = 0; x < c; x++) {
        const i = y * c + x;
        // Diagonal sweep coordinate 0..~2 across the grid.
        const diag = (x / c + y / r) / 2;
        // Seeded jitter keeps the wave organic (not a rigid gradient).
        const jitter = rand() * 0.18;
        th[i] = clamp01(
          bandStart +
            diag * (bandEnd - bandStart) * 0.9 +
            jitter * (bandEnd - bandStart),
        );
      }
    }
    thresholds.push(th);
    cols.push(c);
    rows.push(r);
  });

  return { thresholds, cols, rows };
}

/**
 * Render one frame of the dissolve onto `ctx` at progress `p`.
 *
 * Painting order, back to front:
 *  1. Coarse mosaic (level 0) always painted fully first.
 *  2. For each level L ≥ 1, paint only cells whose *parent*
 *     region has subdivided (threshold passed) — finer cells
 *     replace coarser ones, creating the refinement cascade.
 *
 * Because every cell is a precomputed solid-color canvas, a full
 * repaint costs `sum(cells arrived)` drawImage calls — hundreds of
 * microseconds, GPU-composited, no filters.
 */
export function paintWave(
  ctx: CanvasRenderingContext2D,
  pyramid: MosaicPyramid,
  wave: WaveState,
  p: number,
): void {
  const { width: W, height: H } = pyramid;
  const progress = clamp01(p);
  ctx.clearRect(0, 0, W, H);

  for (let li = 0; li < pyramid.levels.length; li++) {
    const level = pyramid.levels[li];
    const th = wave.thresholds[li]!;
    if (th === undefined) continue;
    const { cols: c, rows: r } = level;
    const cw = W / c;
    const ch = H / r;
    // Coarsest level is the always-on backdrop (never any gaps);
    // finer levels paint only their arrived cells on top.
    const isBase = li === 0;
    for (let i = 0; i < level.cells.length; i++) {
      if (!isBase && th[i]! > progress) continue;
      const x = (i % c) * cw;
      const y = Math.floor(i / c) * ch;
      ctx.drawImage(level.cells[i]!, x, y, cw, ch);
    }
  }
}

function clamp01(v: number): number {
  return v < 0 ? 0 : v > 1 ? 1 : v;
}

function perfMarkSafe(name: string, opts?: PerformanceMarkOptions): void {
  try {
    performance.mark(`nobait:${name}`, opts);
  } catch {
    /* instrumentation must never throw */
  }
}
